#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
class frequency
{
private:int a[100],n,ele,count;
public:void input();
       viod findfreq();
       viod display();
{;
void frequency::input()
{
cout<<"enter the size on an array:";
cin>>n;
cout<<"enter the array elements "<<endl:
for(int i=0;i<n:i++
cin>>a[i];
cout<<"enter the element to find frequency";
cin>>ele;
}
void frequency::findfreq()
{
count=0;
for(int i=0;